language: en-US

reviews:
  auto_review:
    enabled: true
    base_branches:
      - develop
  path_filters:
    - "**/*.js"
    - "**/*.ts"
    - "**/*.json"
    - "**/*.yaml"
    - "**/*.yml"
    - "!node_modules/**"
    - "!*.log"
    - "!.git/**"
    - "!**/plans/**"
    - "!**/starting_files/**"
